# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RN_UI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN_UI

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  
  # Add these to your Podfile
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'RN_UI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

#    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

#    pod 'react-native-locale', :path => '../node_modules/react-native-locale'

#    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  end

  target 'RN_UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RN_UI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN_UI-tvOS

  #target 'RN_UI-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
