# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RN_UI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN_UI

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'RN_UI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

#    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

#    pod 'react-native-locale', :path => '../node_modules/react-native-locale'

#    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  end

  target 'RN_UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RN_UI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN_UI-tvOS

  #target 'RN_UI-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
