# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn2

  pod 'Firebase/Core'
  pod 'FBSDKLoginKit'
  
  # twitter
  pod 'TwitterKit', '~> 3.3.0'

  target 'rn2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
#    pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  end

  target 'rn2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'rn2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn2-tvOS

#  target 'rn2-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#end
